def addiotoin(x, y):
    X = 10
    y= 20
print( "addition:" , X + b )
try:
    addiotoin(10 , 20)
    print("operation is successful")
except NameError
    print ("  operaation complete ")